### ISSUE TITLE
twilio autopilot:webhooks:create doesn't accept multiple webhook events

### ISSUE THREAD

**Issue by pranavdesh** [dabblelab/twilio-cli-autopilot-plugin#10]
Works only if you provide one webhook event

![image](https://user-images.githubusercontent.com/18407304/66874339-ad4dcf00-ef5f-11e9-8d48-27112a9c2f99.png)

**Comment by Mohammad-Khalid** [comment]
Hey @pranavdesh you will have to provide multiple webhook events in a single string as below
`twilio autopilot:webhooks:create -s UA32a673a6e5bcf2bba64196bcd6210209 -e "onDialogueStart onDialogueEnd" -u https://almond-cockroach-2282.twil.io/webhook-events -w fromCL`

**Comment by pranavdesh** [comment]
Thanks @Mohammad-Khalid , this works. Closing this issue.
