### ISSUE TITLE
Cannot export assistant

### ISSUE THREAD

**Issue by oliverxu07** [dabblelab/twilio-cli-autopilot-plugin#35]
I get this error when trying to export an assistant:
`ERROR: TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received an instance of NodeError`

Any ideas for debugging?

**Comment by tingiris** [comment]
Hi @oliverxu07 - we pushed an update that I believe resolves this. Can you update the plugin `twilio plugins:update` and let me know if that resolved it for you? Thanks!

**Comment by oliverxu07** [comment]
Hi @tingiris , yes the update resolved it for me! Thanks so much for following up.

**Comment by tingiris** [comment]
Awesome! Thanks for brining it to our attention @oliverxu07.
